"""
This code tries to decrypt an output generated by encrypt() of encrypt_for_decrypt_2.py.

Find and fix the bug(s)!

Author: Omer Rosenbaum
"""
SECRET = "30,Q|{4-s|tr-|-r-dnpur-n{q-r-Ornx}|v{-ny|{t-ur-n;;;"


def decrypt(encrypted):
    (offset, encrypted_string) = encrypted.split(',')
    offset = (int(offset) - 4) // 2  # changed the formula of calculation
    for i in range(len(encrypted_string)):  # the loop was changed  for "one time run" by the encrypted string
        new_char = chr(ord(encrypted_string[i]) - offset)
        encrypted_string = encrypted_string[:i] + encrypted_string[i:].replace(encrypted_string[i], new_char, 1)
    return encrypted_string


if __name__ == "__main__":
    print(decrypt(SECRET))
